# Generated by Django 3.1.7 on 2021-05-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='key',
            field=models.IntegerField(default=0),
        ),
    ]
