# Generated by Django 3.1.7 on 2021-04-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client_location',
            unique_together={('client', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='client_phone',
            unique_together={('client', 'phone')},
        ),
    ]
