# Generated by Django 3.1.7 on 2021-05-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210501_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_location',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
