# Generated by Django 3.1.7 on 2021-05-03 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210501_1323'),
        ('order', '0002_auto_20210502_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client_location'),
        ),
    ]
