# Generated by Django 3.1.7 on 2021-04-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='img',
            field=models.ImageField(null=True, upload_to='brands_imgs/'),
        ),
    ]
